### PR TITLE
Adds pirates as user and pirate ports in fixtures.Updates test for pirate ports.

### PR DESCRIPTION
**Pull request by apoorvaeternity**

### CODE REVIEW

**Comment by apoorvaeternity** [comment]
I have added a pirate user and five pirate ports in db.json.I have updated the tests also.

**Comment by apoorvaeternity** [comment]
I have added a pirate user and five pirate ports in db.json.I have updated the tests also.

**Comment by utkbansal** [comment]
@apoorvaeternity is this still WIP?

**Comment by apoorvaeternity** [comment]
@utkbansal it's done from my side.

**Pull request merged**
